image:
  repository: ghcr.io/sergej-busch/backend
  tag: latest
  pullPolicy: Always

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: hello.ah-ne.in
      paths:
        - path: /hello
          pathType: Prefix
#        - path: /api
#          pathType: Prefix
#    - host: another.ah-ne.in
#      paths:
#        - path: /foo
#          pathType: Prefix

service:
  port: 8080
