image: ghcr.io/sergej-busch/backend:latest
  repository: ghcr.io/sergej-busch/backend
  tag: latest
  pullPolicy: Always

service:
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: hello.ah-ne.in
      paths:
        - path: /
          pathType: ImplementationSpecific
