image: ghcr.io/sergej-busch/backend:latest
  repository: ghcr.io/sergej-busch/backend
  tag: latest
  pullPolicy: Always

service:
  port: 80

ingress:
  enabled: true
  ingressClassName: nginx
  host: hello.ah-ne.in
  path: /
  pathType: ImplementationSpecific