image:
  repository: ghcr.io/sergej-busch/backend
  tag: latest
  pullPolicy: Always

service:
  port: 8080

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: hello.ah-ne.in
      paths:
        - path: /hello
          pathType: Prefix
        - path: /
          pathType: Prefix