image:
  repository: ghcr.io/sergej-busch/backend
  tag: latest
  pullPolicy: Always

service:
  port: 8080

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
  hosts:
    - host: hello.ah-ne.in
      paths:
        - path: /hello
          pathType: Prefix
        - path: /
          pathType: Prefix